// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/custodian/enums.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GCP Regions
type Region int32

const (
	Region_REGION_UNSPECIFIED     Region = 0
	Region_REGION_US_CENTRAL1     Region = 1
	Region_REGION_US_EAST1        Region = 2
	Region_REGION_US_EAST4        Region = 3
	Region_REGION_US_WEST1        Region = 4
	Region_REGION_US_WEST2        Region = 5
	Region_REGION_US_WEST3        Region = 6
	Region_REGION_US_WEST4        Region = 7
	Region_REGION_EUROPE_WEST1    Region = 8
	Region_REGION_EUROPE_WEST2    Region = 9
	Region_REGION_EUROPE_WEST3    Region = 10
	Region_REGION_EUROPE_WEST4    Region = 11
	Region_REGION_EUROPE_WEST6    Region = 12
	Region_REGION_EUROPE_NORTH1   Region = 13
	Region_REGION_ASIA_EAST1      Region = 14
	Region_REGION_ASIA_EAST2      Region = 15
	Region_REGION_ASIA_NORTHEAST1 Region = 16
	Region_REGION_ASIA_NORTHEAST2 Region = 17
	Region_REGION_ASIA_NORTHEAST3 Region = 18
	Region_REGION_ASIA_SOUTH1     Region = 19
	Region_REGION_ASIA_SOUTHEAST1 Region = 20
	Region_REGION_ASIA_SOUTHEAST2 Region = 21
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0:  "REGION_UNSPECIFIED",
		1:  "REGION_US_CENTRAL1",
		2:  "REGION_US_EAST1",
		3:  "REGION_US_EAST4",
		4:  "REGION_US_WEST1",
		5:  "REGION_US_WEST2",
		6:  "REGION_US_WEST3",
		7:  "REGION_US_WEST4",
		8:  "REGION_EUROPE_WEST1",
		9:  "REGION_EUROPE_WEST2",
		10: "REGION_EUROPE_WEST3",
		11: "REGION_EUROPE_WEST4",
		12: "REGION_EUROPE_WEST6",
		13: "REGION_EUROPE_NORTH1",
		14: "REGION_ASIA_EAST1",
		15: "REGION_ASIA_EAST2",
		16: "REGION_ASIA_NORTHEAST1",
		17: "REGION_ASIA_NORTHEAST2",
		18: "REGION_ASIA_NORTHEAST3",
		19: "REGION_ASIA_SOUTH1",
		20: "REGION_ASIA_SOUTHEAST1",
		21: "REGION_ASIA_SOUTHEAST2",
	}
	Region_value = map[string]int32{
		"REGION_UNSPECIFIED":     0,
		"REGION_US_CENTRAL1":     1,
		"REGION_US_EAST1":        2,
		"REGION_US_EAST4":        3,
		"REGION_US_WEST1":        4,
		"REGION_US_WEST2":        5,
		"REGION_US_WEST3":        6,
		"REGION_US_WEST4":        7,
		"REGION_EUROPE_WEST1":    8,
		"REGION_EUROPE_WEST2":    9,
		"REGION_EUROPE_WEST3":    10,
		"REGION_EUROPE_WEST4":    11,
		"REGION_EUROPE_WEST6":    12,
		"REGION_EUROPE_NORTH1":   13,
		"REGION_ASIA_EAST1":      14,
		"REGION_ASIA_EAST2":      15,
		"REGION_ASIA_NORTHEAST1": 16,
		"REGION_ASIA_NORTHEAST2": 17,
		"REGION_ASIA_NORTHEAST3": 18,
		"REGION_ASIA_SOUTH1":     19,
		"REGION_ASIA_SOUTHEAST1": 20,
		"REGION_ASIA_SOUTHEAST2": 21,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[0].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[0]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{0}
}

// GCP Zones
type Zone int32

const (
	Zone_ZONE_UNSPECIFIED    Zone = 0
	Zone_ZONE_US_CENTRAL1_A  Zone = 1
	Zone_ZONE_US_CENTRAL1_B  Zone = 2
	Zone_ZONE_US_CENTRAL1_C  Zone = 3
	Zone_ZONE_US_CENTRAL1_F  Zone = 4
	Zone_ZONE_US_EAST1_B     Zone = 5
	Zone_ZONE_US_EAST1_C     Zone = 6
	Zone_ZONE_US_EAST1_D     Zone = 7
	Zone_ZONE_US_EAST4_A     Zone = 8
	Zone_ZONE_US_EAST4_B     Zone = 9
	Zone_ZONE_US_EAST4_C     Zone = 10
	Zone_ZONE_US_WEST1_A     Zone = 11
	Zone_ZONE_US_WEST1_B     Zone = 12
	Zone_ZONE_US_WEST1_C     Zone = 13
	Zone_ZONE_US_WEST2_A     Zone = 14
	Zone_ZONE_US_WEST2_B     Zone = 15
	Zone_ZONE_US_WEST2_C     Zone = 16
	Zone_ZONE_EUROPE_WEST1_B Zone = 17
	Zone_ZONE_EUROPE_WEST1_C Zone = 18
	Zone_ZONE_EUROPE_WEST1_D Zone = 19
	Zone_ZONE_ASIA_EAST1_A   Zone = 20
	Zone_ZONE_ASIA_EAST1_B   Zone = 21
	Zone_ZONE_ASIA_EAST1_C   Zone = 22
)

// Enum value maps for Zone.
var (
	Zone_name = map[int32]string{
		0:  "ZONE_UNSPECIFIED",
		1:  "ZONE_US_CENTRAL1_A",
		2:  "ZONE_US_CENTRAL1_B",
		3:  "ZONE_US_CENTRAL1_C",
		4:  "ZONE_US_CENTRAL1_F",
		5:  "ZONE_US_EAST1_B",
		6:  "ZONE_US_EAST1_C",
		7:  "ZONE_US_EAST1_D",
		8:  "ZONE_US_EAST4_A",
		9:  "ZONE_US_EAST4_B",
		10: "ZONE_US_EAST4_C",
		11: "ZONE_US_WEST1_A",
		12: "ZONE_US_WEST1_B",
		13: "ZONE_US_WEST1_C",
		14: "ZONE_US_WEST2_A",
		15: "ZONE_US_WEST2_B",
		16: "ZONE_US_WEST2_C",
		17: "ZONE_EUROPE_WEST1_B",
		18: "ZONE_EUROPE_WEST1_C",
		19: "ZONE_EUROPE_WEST1_D",
		20: "ZONE_ASIA_EAST1_A",
		21: "ZONE_ASIA_EAST1_B",
		22: "ZONE_ASIA_EAST1_C",
	}
	Zone_value = map[string]int32{
		"ZONE_UNSPECIFIED":    0,
		"ZONE_US_CENTRAL1_A":  1,
		"ZONE_US_CENTRAL1_B":  2,
		"ZONE_US_CENTRAL1_C":  3,
		"ZONE_US_CENTRAL1_F":  4,
		"ZONE_US_EAST1_B":     5,
		"ZONE_US_EAST1_C":     6,
		"ZONE_US_EAST1_D":     7,
		"ZONE_US_EAST4_A":     8,
		"ZONE_US_EAST4_B":     9,
		"ZONE_US_EAST4_C":     10,
		"ZONE_US_WEST1_A":     11,
		"ZONE_US_WEST1_B":     12,
		"ZONE_US_WEST1_C":     13,
		"ZONE_US_WEST2_A":     14,
		"ZONE_US_WEST2_B":     15,
		"ZONE_US_WEST2_C":     16,
		"ZONE_EUROPE_WEST1_B": 17,
		"ZONE_EUROPE_WEST1_C": 18,
		"ZONE_EUROPE_WEST1_D": 19,
		"ZONE_ASIA_EAST1_A":   20,
		"ZONE_ASIA_EAST1_B":   21,
		"ZONE_ASIA_EAST1_C":   22,
	}
)

func (x Zone) Enum() *Zone {
	p := new(Zone)
	*p = x
	return p
}

func (x Zone) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Zone) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[1].Descriptor()
}

func (Zone) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[1]
}

func (x Zone) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Zone.Descriptor instead.
func (Zone) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{1}
}

// Machine Types
type MachineType int32

const (
	MachineType_MACHINE_UNSPECIFIED    MachineType = 0
	MachineType_MACHINE_E2_MICRO       MachineType = 1
	MachineType_MACHINE_E2_SMALL       MachineType = 2
	MachineType_MACHINE_E2_MEDIUM      MachineType = 3
	MachineType_MACHINE_E2_STANDARD_2  MachineType = 4
	MachineType_MACHINE_E2_STANDARD_4  MachineType = 5
	MachineType_MACHINE_E2_STANDARD_8  MachineType = 6
	MachineType_MACHINE_E2_STANDARD_16 MachineType = 7
	MachineType_MACHINE_N1_STANDARD_1  MachineType = 8
	MachineType_MACHINE_N1_STANDARD_2  MachineType = 9
	MachineType_MACHINE_N1_STANDARD_4  MachineType = 10
	MachineType_MACHINE_N1_STANDARD_8  MachineType = 11
	MachineType_MACHINE_N1_STANDARD_16 MachineType = 12
	MachineType_MACHINE_N2_STANDARD_2  MachineType = 13
	MachineType_MACHINE_N2_STANDARD_4  MachineType = 14
	MachineType_MACHINE_N2_STANDARD_8  MachineType = 15
	MachineType_MACHINE_N2_STANDARD_16 MachineType = 16
	MachineType_MACHINE_C2_STANDARD_4  MachineType = 17
	MachineType_MACHINE_C2_STANDARD_8  MachineType = 18
	MachineType_MACHINE_C2_STANDARD_16 MachineType = 19
)

// Enum value maps for MachineType.
var (
	MachineType_name = map[int32]string{
		0:  "MACHINE_UNSPECIFIED",
		1:  "MACHINE_E2_MICRO",
		2:  "MACHINE_E2_SMALL",
		3:  "MACHINE_E2_MEDIUM",
		4:  "MACHINE_E2_STANDARD_2",
		5:  "MACHINE_E2_STANDARD_4",
		6:  "MACHINE_E2_STANDARD_8",
		7:  "MACHINE_E2_STANDARD_16",
		8:  "MACHINE_N1_STANDARD_1",
		9:  "MACHINE_N1_STANDARD_2",
		10: "MACHINE_N1_STANDARD_4",
		11: "MACHINE_N1_STANDARD_8",
		12: "MACHINE_N1_STANDARD_16",
		13: "MACHINE_N2_STANDARD_2",
		14: "MACHINE_N2_STANDARD_4",
		15: "MACHINE_N2_STANDARD_8",
		16: "MACHINE_N2_STANDARD_16",
		17: "MACHINE_C2_STANDARD_4",
		18: "MACHINE_C2_STANDARD_8",
		19: "MACHINE_C2_STANDARD_16",
	}
	MachineType_value = map[string]int32{
		"MACHINE_UNSPECIFIED":    0,
		"MACHINE_E2_MICRO":       1,
		"MACHINE_E2_SMALL":       2,
		"MACHINE_E2_MEDIUM":      3,
		"MACHINE_E2_STANDARD_2":  4,
		"MACHINE_E2_STANDARD_4":  5,
		"MACHINE_E2_STANDARD_8":  6,
		"MACHINE_E2_STANDARD_16": 7,
		"MACHINE_N1_STANDARD_1":  8,
		"MACHINE_N1_STANDARD_2":  9,
		"MACHINE_N1_STANDARD_4":  10,
		"MACHINE_N1_STANDARD_8":  11,
		"MACHINE_N1_STANDARD_16": 12,
		"MACHINE_N2_STANDARD_2":  13,
		"MACHINE_N2_STANDARD_4":  14,
		"MACHINE_N2_STANDARD_8":  15,
		"MACHINE_N2_STANDARD_16": 16,
		"MACHINE_C2_STANDARD_4":  17,
		"MACHINE_C2_STANDARD_8":  18,
		"MACHINE_C2_STANDARD_16": 19,
	}
)

func (x MachineType) Enum() *MachineType {
	p := new(MachineType)
	*p = x
	return p
}

func (x MachineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[2].Descriptor()
}

func (MachineType) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[2]
}

func (x MachineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineType.Descriptor instead.
func (MachineType) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{2}
}

// GCP APIs
type GcpApi int32

const (
	GcpApi_API_UNSPECIFIED       GcpApi = 0
	GcpApi_API_COMPUTE           GcpApi = 1
	GcpApi_API_CONTAINER         GcpApi = 2
	GcpApi_API_SQL_ADMIN         GcpApi = 3
	GcpApi_API_STORAGE           GcpApi = 4
	GcpApi_API_BIGQUERY          GcpApi = 5
	GcpApi_API_PUBSUB            GcpApi = 6
	GcpApi_API_DATAFLOW          GcpApi = 7
	GcpApi_API_MONITORING        GcpApi = 8
	GcpApi_API_LOGGING           GcpApi = 9
	GcpApi_API_IAM               GcpApi = 10
	GcpApi_API_RESOURCE_MANAGER  GcpApi = 11
	GcpApi_API_CLOUD_BUILD       GcpApi = 12
	GcpApi_API_CLOUD_FUNCTIONS   GcpApi = 13
	GcpApi_API_CLOUD_RUN         GcpApi = 14
	GcpApi_API_KUBERNETES_ENGINE GcpApi = 15
	GcpApi_API_CLOUD_DNS         GcpApi = 16
	GcpApi_API_CLOUD_CDN         GcpApi = 17
	GcpApi_API_LOAD_BALANCING    GcpApi = 18
	GcpApi_API_VPC_ACCESS        GcpApi = 19
	GcpApi_API_FIREWALL          GcpApi = 20
)

// Enum value maps for GcpApi.
var (
	GcpApi_name = map[int32]string{
		0:  "API_UNSPECIFIED",
		1:  "API_COMPUTE",
		2:  "API_CONTAINER",
		3:  "API_SQL_ADMIN",
		4:  "API_STORAGE",
		5:  "API_BIGQUERY",
		6:  "API_PUBSUB",
		7:  "API_DATAFLOW",
		8:  "API_MONITORING",
		9:  "API_LOGGING",
		10: "API_IAM",
		11: "API_RESOURCE_MANAGER",
		12: "API_CLOUD_BUILD",
		13: "API_CLOUD_FUNCTIONS",
		14: "API_CLOUD_RUN",
		15: "API_KUBERNETES_ENGINE",
		16: "API_CLOUD_DNS",
		17: "API_CLOUD_CDN",
		18: "API_LOAD_BALANCING",
		19: "API_VPC_ACCESS",
		20: "API_FIREWALL",
	}
	GcpApi_value = map[string]int32{
		"API_UNSPECIFIED":       0,
		"API_COMPUTE":           1,
		"API_CONTAINER":         2,
		"API_SQL_ADMIN":         3,
		"API_STORAGE":           4,
		"API_BIGQUERY":          5,
		"API_PUBSUB":            6,
		"API_DATAFLOW":          7,
		"API_MONITORING":        8,
		"API_LOGGING":           9,
		"API_IAM":               10,
		"API_RESOURCE_MANAGER":  11,
		"API_CLOUD_BUILD":       12,
		"API_CLOUD_FUNCTIONS":   13,
		"API_CLOUD_RUN":         14,
		"API_KUBERNETES_ENGINE": 15,
		"API_CLOUD_DNS":         16,
		"API_CLOUD_CDN":         17,
		"API_LOAD_BALANCING":    18,
		"API_VPC_ACCESS":        19,
		"API_FIREWALL":          20,
	}
)

func (x GcpApi) Enum() *GcpApi {
	p := new(GcpApi)
	*p = x
	return p
}

func (x GcpApi) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GcpApi) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[3].Descriptor()
}

func (GcpApi) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[3]
}

func (x GcpApi) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GcpApi.Descriptor instead.
func (GcpApi) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{3}
}

// Load Balancer Types
type LoadBalancerType int32

const (
	LoadBalancerType_LB_UNSPECIFIED      LoadBalancerType = 0
	LoadBalancerType_LB_HTTP             LoadBalancerType = 1
	LoadBalancerType_LB_HTTPS            LoadBalancerType = 2
	LoadBalancerType_LB_TCP              LoadBalancerType = 3
	LoadBalancerType_LB_UDP              LoadBalancerType = 4
	LoadBalancerType_LB_INTERNAL         LoadBalancerType = 5
	LoadBalancerType_LB_INTERNAL_MANAGED LoadBalancerType = 6
)

// Enum value maps for LoadBalancerType.
var (
	LoadBalancerType_name = map[int32]string{
		0: "LB_UNSPECIFIED",
		1: "LB_HTTP",
		2: "LB_HTTPS",
		3: "LB_TCP",
		4: "LB_UDP",
		5: "LB_INTERNAL",
		6: "LB_INTERNAL_MANAGED",
	}
	LoadBalancerType_value = map[string]int32{
		"LB_UNSPECIFIED":      0,
		"LB_HTTP":             1,
		"LB_HTTPS":            2,
		"LB_TCP":              3,
		"LB_UDP":              4,
		"LB_INTERNAL":         5,
		"LB_INTERNAL_MANAGED": 6,
	}
)

func (x LoadBalancerType) Enum() *LoadBalancerType {
	p := new(LoadBalancerType)
	*p = x
	return p
}

func (x LoadBalancerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[4].Descriptor()
}

func (LoadBalancerType) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[4]
}

func (x LoadBalancerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerType.Descriptor instead.
func (LoadBalancerType) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{4}
}

// Reserved IP Types
type ReservedIpType int32

const (
	ReservedIpType_RESERVED_IP_UNSPECIFIED ReservedIpType = 0
	ReservedIpType_GLOBAL                  ReservedIpType = 1
	ReservedIpType_REGIONAL                ReservedIpType = 2
)

// Enum value maps for ReservedIpType.
var (
	ReservedIpType_name = map[int32]string{
		0: "RESERVED_IP_UNSPECIFIED",
		1: "GLOBAL",
		2: "REGIONAL",
	}
	ReservedIpType_value = map[string]int32{
		"RESERVED_IP_UNSPECIFIED": 0,
		"GLOBAL":                  1,
		"REGIONAL":                2,
	}
)

func (x ReservedIpType) Enum() *ReservedIpType {
	p := new(ReservedIpType)
	*p = x
	return p
}

func (x ReservedIpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservedIpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[5].Descriptor()
}

func (ReservedIpType) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[5]
}

func (x ReservedIpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservedIpType.Descriptor instead.
func (ReservedIpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{5}
}

// Disk Types
type DiskType int32

const (
	DiskType_DISK_TYPE_UNSPECIFIED DiskType = 0
	DiskType_DISK_TYPE_PD_STANDARD DiskType = 1
	DiskType_DISK_TYPE_PD_SSD      DiskType = 2
	DiskType_DISK_TYPE_PD_BALANCED DiskType = 3
	DiskType_DISK_TYPE_LOCAL_SSD   DiskType = 4
)

// Enum value maps for DiskType.
var (
	DiskType_name = map[int32]string{
		0: "DISK_TYPE_UNSPECIFIED",
		1: "DISK_TYPE_PD_STANDARD",
		2: "DISK_TYPE_PD_SSD",
		3: "DISK_TYPE_PD_BALANCED",
		4: "DISK_TYPE_LOCAL_SSD",
	}
	DiskType_value = map[string]int32{
		"DISK_TYPE_UNSPECIFIED": 0,
		"DISK_TYPE_PD_STANDARD": 1,
		"DISK_TYPE_PD_SSD":      2,
		"DISK_TYPE_PD_BALANCED": 3,
		"DISK_TYPE_LOCAL_SSD":   4,
	}
)

func (x DiskType) Enum() *DiskType {
	p := new(DiskType)
	*p = x
	return p
}

func (x DiskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[6].Descriptor()
}

func (DiskType) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[6]
}

func (x DiskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskType.Descriptor instead.
func (DiskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{6}
}

// Network Tier
type NetworkTier int32

const (
	NetworkTier_NETWORK_TIER_UNSPECIFIED NetworkTier = 0
	NetworkTier_NETWORK_TIER_PREMIUM     NetworkTier = 1
	NetworkTier_NETWORK_TIER_STANDARD    NetworkTier = 2
)

// Enum value maps for NetworkTier.
var (
	NetworkTier_name = map[int32]string{
		0: "NETWORK_TIER_UNSPECIFIED",
		1: "NETWORK_TIER_PREMIUM",
		2: "NETWORK_TIER_STANDARD",
	}
	NetworkTier_value = map[string]int32{
		"NETWORK_TIER_UNSPECIFIED": 0,
		"NETWORK_TIER_PREMIUM":     1,
		"NETWORK_TIER_STANDARD":    2,
	}
)

func (x NetworkTier) Enum() *NetworkTier {
	p := new(NetworkTier)
	*p = x
	return p
}

func (x NetworkTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_custodian_enums_proto_enumTypes[7].Descriptor()
}

func (NetworkTier) Type() protoreflect.EnumType {
	return &file_proto_custodian_enums_proto_enumTypes[7]
}

func (x NetworkTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkTier.Descriptor instead.
func (NetworkTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_custodian_enums_proto_rawDescGZIP(), []int{7}
}

var File_proto_custodian_enums_proto protoreflect.FileDescriptor

const file_proto_custodian_enums_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/custodian/enums.proto\x12\tcustodian*\x9f\x04\n" +
	"\x06Region\x12\x16\n" +
	"\x12REGION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12REGION_US_CENTRAL1\x10\x01\x12\x13\n" +
	"\x0fREGION_US_EAST1\x10\x02\x12\x13\n" +
	"\x0fREGION_US_EAST4\x10\x03\x12\x13\n" +
	"\x0fREGION_US_WEST1\x10\x04\x12\x13\n" +
	"\x0fREGION_US_WEST2\x10\x05\x12\x13\n" +
	"\x0fREGION_US_WEST3\x10\x06\x12\x13\n" +
	"\x0fREGION_US_WEST4\x10\a\x12\x17\n" +
	"\x13REGION_EUROPE_WEST1\x10\b\x12\x17\n" +
	"\x13REGION_EUROPE_WEST2\x10\t\x12\x17\n" +
	"\x13REGION_EUROPE_WEST3\x10\n" +
	"\x12\x17\n" +
	"\x13REGION_EUROPE_WEST4\x10\v\x12\x17\n" +
	"\x13REGION_EUROPE_WEST6\x10\f\x12\x18\n" +
	"\x14REGION_EUROPE_NORTH1\x10\r\x12\x15\n" +
	"\x11REGION_ASIA_EAST1\x10\x0e\x12\x15\n" +
	"\x11REGION_ASIA_EAST2\x10\x0f\x12\x1a\n" +
	"\x16REGION_ASIA_NORTHEAST1\x10\x10\x12\x1a\n" +
	"\x16REGION_ASIA_NORTHEAST2\x10\x11\x12\x1a\n" +
	"\x16REGION_ASIA_NORTHEAST3\x10\x12\x12\x16\n" +
	"\x12REGION_ASIA_SOUTH1\x10\x13\x12\x1a\n" +
	"\x16REGION_ASIA_SOUTHEAST1\x10\x14\x12\x1a\n" +
	"\x16REGION_ASIA_SOUTHEAST2\x10\x15*\x88\x04\n" +
	"\x04Zone\x12\x14\n" +
	"\x10ZONE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ZONE_US_CENTRAL1_A\x10\x01\x12\x16\n" +
	"\x12ZONE_US_CENTRAL1_B\x10\x02\x12\x16\n" +
	"\x12ZONE_US_CENTRAL1_C\x10\x03\x12\x16\n" +
	"\x12ZONE_US_CENTRAL1_F\x10\x04\x12\x13\n" +
	"\x0fZONE_US_EAST1_B\x10\x05\x12\x13\n" +
	"\x0fZONE_US_EAST1_C\x10\x06\x12\x13\n" +
	"\x0fZONE_US_EAST1_D\x10\a\x12\x13\n" +
	"\x0fZONE_US_EAST4_A\x10\b\x12\x13\n" +
	"\x0fZONE_US_EAST4_B\x10\t\x12\x13\n" +
	"\x0fZONE_US_EAST4_C\x10\n" +
	"\x12\x13\n" +
	"\x0fZONE_US_WEST1_A\x10\v\x12\x13\n" +
	"\x0fZONE_US_WEST1_B\x10\f\x12\x13\n" +
	"\x0fZONE_US_WEST1_C\x10\r\x12\x13\n" +
	"\x0fZONE_US_WEST2_A\x10\x0e\x12\x13\n" +
	"\x0fZONE_US_WEST2_B\x10\x0f\x12\x13\n" +
	"\x0fZONE_US_WEST2_C\x10\x10\x12\x17\n" +
	"\x13ZONE_EUROPE_WEST1_B\x10\x11\x12\x17\n" +
	"\x13ZONE_EUROPE_WEST1_C\x10\x12\x12\x17\n" +
	"\x13ZONE_EUROPE_WEST1_D\x10\x13\x12\x15\n" +
	"\x11ZONE_ASIA_EAST1_A\x10\x14\x12\x15\n" +
	"\x11ZONE_ASIA_EAST1_B\x10\x15\x12\x15\n" +
	"\x11ZONE_ASIA_EAST1_C\x10\x16*\x9d\x04\n" +
	"\vMachineType\x12\x17\n" +
	"\x13MACHINE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MACHINE_E2_MICRO\x10\x01\x12\x14\n" +
	"\x10MACHINE_E2_SMALL\x10\x02\x12\x15\n" +
	"\x11MACHINE_E2_MEDIUM\x10\x03\x12\x19\n" +
	"\x15MACHINE_E2_STANDARD_2\x10\x04\x12\x19\n" +
	"\x15MACHINE_E2_STANDARD_4\x10\x05\x12\x19\n" +
	"\x15MACHINE_E2_STANDARD_8\x10\x06\x12\x1a\n" +
	"\x16MACHINE_E2_STANDARD_16\x10\a\x12\x19\n" +
	"\x15MACHINE_N1_STANDARD_1\x10\b\x12\x19\n" +
	"\x15MACHINE_N1_STANDARD_2\x10\t\x12\x19\n" +
	"\x15MACHINE_N1_STANDARD_4\x10\n" +
	"\x12\x19\n" +
	"\x15MACHINE_N1_STANDARD_8\x10\v\x12\x1a\n" +
	"\x16MACHINE_N1_STANDARD_16\x10\f\x12\x19\n" +
	"\x15MACHINE_N2_STANDARD_2\x10\r\x12\x19\n" +
	"\x15MACHINE_N2_STANDARD_4\x10\x0e\x12\x19\n" +
	"\x15MACHINE_N2_STANDARD_8\x10\x0f\x12\x1a\n" +
	"\x16MACHINE_N2_STANDARD_16\x10\x10\x12\x19\n" +
	"\x15MACHINE_C2_STANDARD_4\x10\x11\x12\x19\n" +
	"\x15MACHINE_C2_STANDARD_8\x10\x12\x12\x1a\n" +
	"\x16MACHINE_C2_STANDARD_16\x10\x13*\xa5\x03\n" +
	"\x06GcpApi\x12\x13\n" +
	"\x0fAPI_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vAPI_COMPUTE\x10\x01\x12\x11\n" +
	"\rAPI_CONTAINER\x10\x02\x12\x11\n" +
	"\rAPI_SQL_ADMIN\x10\x03\x12\x0f\n" +
	"\vAPI_STORAGE\x10\x04\x12\x10\n" +
	"\fAPI_BIGQUERY\x10\x05\x12\x0e\n" +
	"\n" +
	"API_PUBSUB\x10\x06\x12\x10\n" +
	"\fAPI_DATAFLOW\x10\a\x12\x12\n" +
	"\x0eAPI_MONITORING\x10\b\x12\x0f\n" +
	"\vAPI_LOGGING\x10\t\x12\v\n" +
	"\aAPI_IAM\x10\n" +
	"\x12\x18\n" +
	"\x14API_RESOURCE_MANAGER\x10\v\x12\x13\n" +
	"\x0fAPI_CLOUD_BUILD\x10\f\x12\x17\n" +
	"\x13API_CLOUD_FUNCTIONS\x10\r\x12\x11\n" +
	"\rAPI_CLOUD_RUN\x10\x0e\x12\x19\n" +
	"\x15API_KUBERNETES_ENGINE\x10\x0f\x12\x11\n" +
	"\rAPI_CLOUD_DNS\x10\x10\x12\x11\n" +
	"\rAPI_CLOUD_CDN\x10\x11\x12\x16\n" +
	"\x12API_LOAD_BALANCING\x10\x12\x12\x12\n" +
	"\x0eAPI_VPC_ACCESS\x10\x13\x12\x10\n" +
	"\fAPI_FIREWALL\x10\x14*\x83\x01\n" +
	"\x10LoadBalancerType\x12\x12\n" +
	"\x0eLB_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aLB_HTTP\x10\x01\x12\f\n" +
	"\bLB_HTTPS\x10\x02\x12\n" +
	"\n" +
	"\x06LB_TCP\x10\x03\x12\n" +
	"\n" +
	"\x06LB_UDP\x10\x04\x12\x0f\n" +
	"\vLB_INTERNAL\x10\x05\x12\x17\n" +
	"\x13LB_INTERNAL_MANAGED\x10\x06*G\n" +
	"\x0eReservedIpType\x12\x1b\n" +
	"\x17RESERVED_IP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x01\x12\f\n" +
	"\bREGIONAL\x10\x02*\x8a\x01\n" +
	"\bDiskType\x12\x19\n" +
	"\x15DISK_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DISK_TYPE_PD_STANDARD\x10\x01\x12\x14\n" +
	"\x10DISK_TYPE_PD_SSD\x10\x02\x12\x19\n" +
	"\x15DISK_TYPE_PD_BALANCED\x10\x03\x12\x17\n" +
	"\x13DISK_TYPE_LOCAL_SSD\x10\x04*`\n" +
	"\vNetworkTier\x12\x1c\n" +
	"\x18NETWORK_TIER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14NETWORK_TIER_PREMIUM\x10\x01\x12\x19\n" +
	"\x15NETWORK_TIER_STANDARD\x10\x02B\x16Z\x14custodian/pkg/configb\x06proto3"

var (
	file_proto_custodian_enums_proto_rawDescOnce sync.Once
	file_proto_custodian_enums_proto_rawDescData []byte
)

func file_proto_custodian_enums_proto_rawDescGZIP() []byte {
	file_proto_custodian_enums_proto_rawDescOnce.Do(func() {
		file_proto_custodian_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_custodian_enums_proto_rawDesc), len(file_proto_custodian_enums_proto_rawDesc)))
	})
	return file_proto_custodian_enums_proto_rawDescData
}

var file_proto_custodian_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_custodian_enums_proto_goTypes = []any{
	(Region)(0),           // 0: custodian.Region
	(Zone)(0),             // 1: custodian.Zone
	(MachineType)(0),      // 2: custodian.MachineType
	(GcpApi)(0),           // 3: custodian.GcpApi
	(LoadBalancerType)(0), // 4: custodian.LoadBalancerType
	(ReservedIpType)(0),   // 5: custodian.ReservedIpType
	(DiskType)(0),         // 6: custodian.DiskType
	(NetworkTier)(0),      // 7: custodian.NetworkTier
}
var file_proto_custodian_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_custodian_enums_proto_init() }
func file_proto_custodian_enums_proto_init() {
	if File_proto_custodian_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_custodian_enums_proto_rawDesc), len(file_proto_custodian_enums_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_custodian_enums_proto_goTypes,
		DependencyIndexes: file_proto_custodian_enums_proto_depIdxs,
		EnumInfos:         file_proto_custodian_enums_proto_enumTypes,
	}.Build()
	File_proto_custodian_enums_proto = out.File
	file_proto_custodian_enums_proto_goTypes = nil
	file_proto_custodian_enums_proto_depIdxs = nil
}
